### ISSUE TITLE
Please provide a arm64 macOS way to compile

### ISSUE THREAD

**Issue by YunaBraska** [henricj/dunelegacy#48] opened 2023-12-20 13:52 UTC
Hi,

I would like to compile the game on my Apple Silicon (aarch64) machine.
I have no idea about C and Visual Studio. Can you just provide a command or Unix script to install the dependencies and build the project? Would be awesome!

**Comment by henricj** [comment] 2023-12-22 12:17
In theory, the Linux instructions should work, but there are some problems with the build on macOS.  A while back, I even bought a Mac mini to try to address these build issues (which I can't recall off the top of my head), but I've been too busy to look at it.

This is supposed to work:
```
mkdir -p out/build/arm64-release
cmake --preset macos-arm64-release -B out/build/arm64-release
cmake --build out/build/arm64-release
ctest
```
and gets further in https://github.com/henricj/dunelegacy/tree/mac-build than the default "modernize" branch.  But more work is needed.

**Comment by henricj** [comment] 2023-12-22 14:18
Most of the problems seem to have been resolved when building with [Xcode 15](https://developer.apple.com/xcode/).  In earlier versions, Xcode's poor [`std::ranges`](https://en.cppreference.com/w/cpp/ranges) support had led to many compiler errors.  There are still some linker issues, but everything is at least compiling now (on the [mac-build](https://github.com/henricj/dunelegacy/tree/mac-build) branch, anyway).

**Comment by henricj** [comment] 2024-02-12 01:08
It now compiles on macOS and the tests pass, but the main application fails soon after start (at least on an M2 mini running Sonoma 14.3.1).

**Comment by henricj** [comment] 2024-03-07 21:04
Duplicate of #3

**Closed as completed by henricj** 2024-03-07 21:04 UTC
Labels: help wanted, build
